name: action-agent

description: Run Codex CLI for GitHub events like issues, pull requests, comments, schedules, and manual dispatches.

inputs:
  api_key:
    description: Model provider API key
    required: true
  github_token:
    description: GitHub token used for GitHub API + MCP
    required: true
  model:
    description: Codex model override
    required: false
    default: ""
  reasoning_effort:
    description: Codex reasoning effort override
    required: false
    default: ""
  prompt:
    description: Optional extra instructions for the agent
    required: false
    default: ""
  resume:
    description: Enable session resume across runs
    required: false

runs:
  using: node20
  main: dist/index.js
