name: workflow-agent
author: sudden-network

description: Run programmable agents on any GitHub Workflow to enable automation across your repo.

inputs:
  agent_api_key:
    description: Agent API key
    required: true
  github_token:
    description: GitHub token used by the action
    required: true
  agent:
    description: Agent to run
    required: false
    default: codex
  model:
    description: Agent model override (for Codex, append reasoning effort with /, e.g. gpt-5.2-codex/xhigh)
    required: false
    default: ""
  prompt:
    description: Optional extra instructions for the agent
    required: false
    default: ""
  resume:
    description: Enable session resume across runs
    required: false

runs:
  using: node20
  main: dist/index.js
