name: Codex Worker

description: Run Codex CLI for issue/issue_comment threads.

inputs:
  issue_number:
    description: GitHub issue number
    required: true
  comment_id:
    description: GitHub comment ID (optional)
    required: false
    default: ""
  model:
    description: Codex model override (optional)
    required: false
    default: ""
  reasoning_effort:
    description: Codex reasoning effort override (optional)
    required: false
    default: ""
  timeout_minutes:
    description: Maximum execution time in minutes (default 30)
    required: false
    default: "30"
  max_output_size:
    description: Maximum output size in bytes before truncation (default 10MB)
    required: false
    default: "10485760"
  openai_api_key:
    description: OpenAI API key
    required: true
  github_token:
    description: GitHub token used for API + gh
    required: true

runs:
  using: node20
  main: dist/index.js
